version: '3.7'
services:
  web:
    build: .
    image: gowebapp
    restart: always
    ports:
      - 8081:8081
  db:
    image: postgres
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - "rabbitmq_data:/data"
volumes:
  rabbitmq_data: